### ISSUE TITLE
8 sites missing in-site-metrics.csv

### ISSUE THREAD

**Issue by Siequnu** [cyipt/actdev#110]
- [ ] Handforth
- [ ] Halsnead
- [ ] Tresham
- [ ] Long Marston
- [ ] Dunton Hills
- [ ] Culm
- [ ] Bailrigg
- [ ] Ashton

**Comment by Robinlovelace** [comment]
These haven't yet been built. There is a 'built' TRUE/FALSE variable somewhere that defines this. Reasoning: hard to calculate metrics for places that do not yet exist.

**Comment by mvl22** [comment]
Reopening so that @Siequnu can validate that this scenario is properly handled.

**Comment by Robinlovelace** [comment]
Shouldn't issues that can be fixed with code in the ui repo be tracked there? Will leave this one here for now but in general I suggest that is how we use issues: to track clearly actionable and well-defined tasks that have been decided on and can be fixed in code. On a wider note, comparing https://github.com/cyipt/acton/issues with https://github.com/cyipt/actdev/issues I think we've used issues more effectively this time around, but that's going further off topic!

**Comment by mvl22** [comment]
> Shouldn't issues that can be fixed with code in the ui repo be tracked there?

Yes, but it's 1am in the morning and my ability to disambiguate the two in a sea of notifications is perhaps lacking :)

**Comment by Robinlovelace** [comment]
Replaced by https://github.com/cyipt/actdev-ui/issues/32
